services:
  auth-service:
    container_name: user_service
    build: ./
    ports:
      - "8088:8088"
    networks:
      - global
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    networks:
      - global
    volumes:
      - mongo_data:/data/db


networks:
  global:
    driver: bridge

volumes:
  mongo_data: